#define LOCALHOST "0.0.0.0"

// Storage Engine Node
#define OPENCSD_CLUSTER_MASTER_IP getenv("OPENCSD_CLUSTER_MASTER_IP")
#define SE_INTERFACE_PORT 40200
#define SE_INTERFACE_NODE_PORT getenv("SE_INTERFACE_NODE_PORT")

#define SE_OFFLOADING_PORT 40201
#define SE_OFFLOADING_NODE_PORT getenv("SE_OFFLOADING_NODE_PORT")

#define SE_MERGING_PORT 40202
#define SE_MERGING_NODE_PORT getenv("SE_MERGING_NODE_PORT")
#define SE_MERGING_TCP_PORT 40204
#define SE_MERGING_TCP_NODE_PORT getenv("SE_MERGING_TCP_NODE_PORT")
#define T_SE_MERGING_TCP_PORT 40209
#define T_SE_MERGING_TCP_NODE_PORT getenv("T_SE_MERGING_TCP_NODE_PORT")

#define SE_MONITORING_PORT 40203
#define SE_MONITORING_NODE_PORT getenv("SE_MONITORING_NODE_PORT")

// Storage Node 
#define STORAGE_NODE_IP getenv("STORAGE_NODE_IP")
#define CSD_IDENTIFIER_PORT getenv("CSD_IDENTIFIER_PORT")
#define LBA2PBA_MANAGER_PORT getenv("LBA2PBA_MANAGER_PORT")
#define WAL_MANAGER_PORT getenv("WAL_MANAGER_PORT")