#define LOCALHOST "0.0.0.0"

// Storage Engine Node
#define SE_INTERFACE_PORT 40200
#define SE_OFFLOADING_PORT 40201
#define SE_MERGING_PORT 40202
#define SE_MERGING_TCP_PORT 40204
#define T_SE_MERGING_TCP_PORT 40209

#define SE_MONITORING_PORT 40203

// Storage Node 
#define STORAGE_NODE_IP getenv("STORAGE_NODE_IP")
#define CSD_IDENTIFIER_PORT getenv("CSD_IDENTIFIER_PORT")
#define LBA2PBA_MANAGER_PORT getenv("LBA2PBA_MANAGER_PORT")
#define WAL_MANAGER_PORT getenv("WAL_MANAGER_PORT")